#!/bin/sh

if [ $# -eq 0 ]; then
    vim -c 'autocmd VimLeavePre * if exists(":OpenBrowser") | let [g:gist_open_browser_after_post, g:gist_browser_command] = [1, ":OpenBrowser %URL%"] | endif | Gist'
else
    vim "$1" \
        -c 'if line("$") is 1 && getline(1) ==# "" | q!' \
        -c 'if !exists(":Gist") | q!' \
        -c 'if exists(":OpenBrowser") | let [g:gist_open_browser_after_post, g:gist_browser_command] = [1, ":OpenBrowser %URL%"]' \
        -c 'Gist' \
        -c 'q!'
fi
exit 0
