#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

use HTML::TreeBuilder;
use LWP::UserAgent;
use HTTP::Request;
my $URL = 'http://taruo.net/ip/';


my $content = do {
    my $req = HTTP::Request->new(GET => $URL);
    my $ua = LWP::UserAgent->new;
    my $res = $ua->request($req);
    die "GET $URL: ".$res->status_line."\n" unless $res->is_success;
    # decoded_content() returns undef. (why?)
    $res->content;
};
my $tree = HTML::TreeBuilder->new;
$tree->parse($content);
$tree->eof;
if ($tree->find('body')->as_text =~ /REMOTE_ADDR=([0-9.]+)/) {
    print "$1\n";
}
else {
    die "parse error: Couldn't find IP Address.";
}
